# This workflow will install Python dependencies, run autopep8
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: hw2 tests

on:
  push:
    branches: [ "main", "hw2" ]
  pull_request:
    branches: [ "main", "hw2" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Static analysis with autopep8
      run: |
        pip install --upgrade autopep8
        autopep8 -v --aggressive hw2/hw2_debugging.py