# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: hw2 tests

on:
  push:
    branches: [ "main", "hw2" ]
  pull_request:
    branches: [ "main", "hw2" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest hw2/merge_sort_test.py --cov=. --cov-report=xml
    - name: Static analysis with autopep8
      run: |
        pip install --upgrade autopep8
        autopep8 -v --aggressive hw2/hw2_debugging.py
    - name: Static analysis with pylint
      run: |
        pip install pylint
        pylint hw2/hw2_debugging.py
    - name: Static analysis with pyflakes
      run: |
        pip install pyflakes
        pyflakes hw2/hw2_debugging.py
    - name: Generate pyflakes badge
      run: |
        pip install genbadge[all]
        flake8 ./hw2 --exit-zero --format=html --htmldir ./reports/hw2/flake8 --statistics --tee --output-file flake8stats.txt
        genbadge flake8 --input-file ./reports/hw2/flake8stats.txt
        
